from pathlib import Path
from typing import Union
from ..core.stats import ProjectStats


class MarkdownExporter:
    def __init__(self, stats: ProjectStats):
        self.stats = stats

    def export(self, output_path: Union[str, Path]) -> None:
        output_path = Path(output_path)
        content = self.generate_report()
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    def generate_report(self) -> str:
        lines = []
        
        lines.append("# Code Statistics Report")
        lines.append("")
        lines.append(f"**Project Path:** `{self.stats.root_path}`")
        lines.append("")
        
        lines.append("## Summary")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Files | {self.stats.total_files} |")
        lines.append(f"| Total Lines | {self.stats.total_lines} |")
        lines.append(f"| Code Lines | {self.stats.total_code_lines} |")
        lines.append(f"| Comment Lines | {self.stats.total_comment_lines} |")
        lines.append(f"| Blank Lines | {self.stats.total_blank_lines} |")
        lines.append(f"| Code Percentage | {self.stats.code_percentage:.2f}% |")
        lines.append(f"| Total Size | {self._format_size(self.stats.total_file_size)} |")
        lines.append("")
        
        if self.stats.language_stats:
            lines.append("## Statistics by Language")
            lines.append("")
            lines.append("| Language | Files | Code Lines | Comment Lines | Percentage |")
            lines.append("|----------|-------|------------|---------------|------------|")
            
            sorted_langs = sorted(
                self.stats.language_stats.items(),
                key=lambda x: x[1].code_lines,
                reverse=True,
            )
            
            for lang, lang_stats in sorted_langs:
                percentage = (lang_stats.code_lines / self.stats.total_code_lines * 100) if self.stats.total_code_lines > 0 else 0
                lines.append(
                    f"| {lang} | {lang_stats.files_count} | {lang_stats.code_lines} | "
                    f"{lang_stats.comment_lines} | {percentage:.2f}% |"
                )
            lines.append("")
        
        if self.stats.file_stats:
            lines.append("## Top Files by Code Lines")
            lines.append("")
            lines.append("| File | Language | Code Lines |")
            lines.append("|------|----------|------------|")
            
            top_files = sorted(
                self.stats.file_stats,
                key=lambda x: x.code_lines,
                reverse=True,
            )[:20]
            
            for file_stat in top_files:
                lines.append(
                    f"| `{file_stat.filename}` | {file_stat.language} | {file_stat.code_lines} |"
                )
            lines.append("")
        
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Code Stats*")
        
        return "\n".join(lines)

    def _format_size(self, size_bytes: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if size_bytes < 1024.0:
                return f"{size_bytes:.2f} {unit}"
            size_bytes /= 1024.0
        return f"{size_bytes:.2f} TB"